#!/bin/sh

"$AMSBIN/ams" << eor

Task TransitionStateSearch
Properties
    NormalModes Yes
End
GeometryOptimization
    InitialHessian
        Type Calculate
    End
End
System
    Atoms
        C 0.021942 -0.04426 0.014675 
        H -0.002196 0.004442 1.094692 
        H 1.012557 0.003979 -0.416307 
        H -0.620534 -0.799674 -0.416566 
        H -0.569349 1.157425 -0.38279 
        H -0.94009 1.910918 -0.632008 
    End
    BondOrders
         1 2 1.0
         1 3 1.0
         1 4 1.0
    End
End

Engine ADF
    Basis
        Core None
    End
    SpinPolarization 1
    XC
        Hybrid B3LYP
    End
    Relativity
        Level None
    End
    Unrestricted Yes
EndEngine
eor

