#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
Properties
    NormalModes Yes
End
System
    Atoms
        C -0.006078 -0.038776 -0.253376 
        H 0.96933 -0.448102 -0.481858 
        H -0.182803 0.945333 -0.667467 
        H -0.823574 -0.7335930000000001 -0.395168 
        H 0.02572 0.164102 1.072331 
        H 0.047797 0.304917 1.992418 
    End
    BondOrders
         1 2 1.0
         1 3 1.0
         1 4 1.0
         1 5 1.0
    End
End

Engine ADF
    Basis
        Core None
    End
    SpinPolarization 1
    XC
        GGA BLYP
    End
    Relativity
        Level None
    End
    Unrestricted Yes
EndEngine
eor

